"""project specific attributes

Revision ID: 5de0753431d7
Revises: 4777dc6cf21b
Create Date: 2022-05-08 00:13:47.408805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de0753431d7'
down_revision = '4777dc6cf21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('soc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'soc')
    op.drop_column('user', 'points')
    # ### end Alembic commands ###
